### ISSUE TITLE
how to implement a redis connection pool in lua.

### ISSUE THREAD

**Issue by barretxzh** [openresty/lua-resty-redis#56]
i am trying to use lua-resty-redis in my web server which for a game. 
it  works very nice when there are few requests per second.
but the cost of close the sokect is too expensive when request  frequently.
so i want to implement a redis connection pool for each nginx worker.
we cannot use upstream in the lua code to access redis server ,am i right? 
how to do it?

**Comment by agentzh** [comment]
There *is* a builtin connection pool facility (provided by ngx_lua). Check out the set_keepalive() method of the rest.rdis object in lua-resty-redis's documentation.

**Comment by barretxzh** [comment]
sorry to trouble you again.
according to your suggestion.i use set_keepalive method in the end of one request.
but it seems to be very strange that when processing another request  the connect function in resty.redis do not reuse the pre connection but create a new one.and after the ngx_http_lua_socket_tcp_setkeepalive was finished the pre connection was close by nginx worker.

tcpdump :
![1](https://cloud.githubusercontent.com/assets/5162809/5913237/66dcf916-a61b-11e4-92ac-993f7bd180dd.jpg)

gdb:
![4](https://cloud.githubusercontent.com/assets/5162809/5913245/79ca42fe-a61b-11e4-934c-b8efc9ce5786.png)
![5](https://cloud.githubusercontent.com/assets/5162809/5913246/7bb64e32-a61b-11e4-9029-0937d6d84321.jpg)

**Comment by agentzh** [comment]
@barretxzh Try running the minimal example in the Synopsis documentation section:

https://github.com/openresty/lua-resty-redis#synopsis

My hunch is that you call `set_keepalive` in the wrong way and because the code snippet you provide is far from complete, I cannot really help you. Ensure you have read the code examples and other parts of the documentation carefully.

BTW, please always try providing a standalone and minimal example with precise steps that can help reproducing what you're seeing on others' boxes. Otherwise, it is always too little or too much information for us to diagnose.

**Comment by gitnewer** [comment]
I have a question. If I don't use "set_keepalive" and "close" ,what will happen? The redis server will have too many unclosed redis connections  ?

**Comment by agentzh** [comment]
@gitnewer Such connections are subject to the Lua/LuaJIT garbage collection. When the cosocket Lua object gets collected its underlying TCP connection (if any) gets closed immediately.

**Comment by gitnewer** [comment]
@agentzh Thank you very much！
