### ISSUE TITLE
Why we need connection pool?

### ISSUE THREAD

**Issue by wyTrivail** [openresty/lua-resty-redis#94]
As we all known that the cosocket is a asynchronous IO api, why not we just use one redis connection per worker?  
I think asynchronous IO do not need multi thread pool at the level of redis.
waiting you answer, tks!

**Comment by agentzh** [comment]
@wyTrivail First of all, "asynchronous IO" is a misleading and ambiguous term. Better avoid it. We use the terms "nonblocking I/O" and "I/O multiplexing" instead.

The reason why we do not use one redis connection per nginx worker is because that redis connections do not support connection-level request multiplexing, which means if you have `N` nginx worker processes, then you only have a backend concurrency level of `N` at most, which is VERY limited (not really better than Apache's prefork mpm using blocking I/O).

**Comment by wyTrivail** [comment]
thanks for your answer, i have got it.
so,  any redis client like ioredis, predis also use connection pool, is it right?

**Comment by agentzh** [comment]
@wyTrivail I have no idea about other redis clients like ioredis or predis. Sorry.
